### PR TITLE
Web VR Input system

### PR DESCRIPTION
**Pull request by lusianm**
Test View

image

The Branch for create VRoom Input System.
This Input System concentrate Desktop Input and VR Controller Input, and automatically change VR Input mode to Desktop Input Mode or reversely depending on bool variable is VR Mode or Desktop Mode.
Also you can get each input separately.

Web XR Reference Youtube : https://www.youtube.com/watch?v=nPAHZ9Rm8d4
Web XR Package GitHub Url : https://github.com/De-Panther/unity-webxr-export

### CODE REVIEW

**Comment by Snowapril** [comment]
image
Is this normal in `SampleScene`?

**Comment by lusianm** [comment]
I Move Test Scene From WebXR/.../Samples/... to Scenes folder.
Now you can check my test in Assets/Scenes/WebXRTestScene.

**Comment by lusianm** [comment]
Change Gitignore

**Review by Snowapril — APPROVED** [review]
Now it seems great in my environment too! Thanks for your work 👍

**Pull request merged**
